//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN
    {
        public int IDN { get; set; }
        public int IDP { get; set; }
        public int IDG { get; set; }
        public int IDD { get; set; }
        public string Ned_1 { get; set; }
        public string Ned_2 { get; set; }
        public string Ned_3 { get; set; }
        public string Ned_4 { get; set; }
        public string Ned_5 { get; set; }
        public string Ned_6 { get; set; }
        public string Ned_7 { get; set; }
        public string Ned_8 { get; set; }
        public string Ned_9 { get; set; }
        public string Ned_10 { get; set; }
        public string Ned_11 { get; set; }
        public string Ned_12 { get; set; }
        public string Ned_13 { get; set; }
        public string Ned_14 { get; set; }
        public string Ned_15 { get; set; }
        public string Ned_16 { get; set; }
        public string Ned_17 { get; set; }
        public string Ned_18 { get; set; }
        public string Ned_19 { get; set; }
        public string Ned_20 { get; set; }
        public string Ned_21 { get; set; }
        public string Ned_22 { get; set; }
        public string Ned_23 { get; set; }
        public string Ned_24 { get; set; }
        public string Ned_25 { get; set; }
        public string Ned_26 { get; set; }
        public string Ned_27 { get; set; }
        public string Ned_28 { get; set; }
    }
}
