//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPPREP
    {
        public int IDP { get; set; }
        public Nullable<int> IDK { get; set; }
        public Nullable<int> IDA { get; set; }
        public Nullable<short> IP { get; set; }
        public string MEMO { get; set; }
        public string TABNOM { get; set; }
        public string ADRESS { get; set; }
        public string PHONE { get; set; }
        public string FAMIO { get; set; }
    }
}
