//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ExRaspisDBEntities : DbContext
    {
        public ExRaspisDBEntities()
            : base("name=ExRaspisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NED> NED { get; set; }
        public virtual DbSet<PLAN> PLAN { get; set; }
        public virtual DbSet<PLANtemp> PLANtemp { get; set; }
        public virtual DbSet<SPGRUP> SPGRUP { get; set; }
        public virtual DbSet<SPNAGR> SPNAGR { get; set; }
        public virtual DbSet<SPPRED> SPPRED { get; set; }
        public virtual DbSet<SPPREP> SPPREP { get; set; }
        public virtual DbSet<UROKI> UROKI { get; set; }
    
        public virtual ObjectResult<Nullable<int>> CountUroki(Nullable<int> iDP, Nullable<int> iDG, Nullable<int> iDD, Nullable<System.DateTime> dAT)
        {
            var iDPParameter = iDP.HasValue ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(int));
    
            var iDGParameter = iDG.HasValue ?
                new ObjectParameter("IDG", iDG) :
                new ObjectParameter("IDG", typeof(int));
    
            var iDDParameter = iDD.HasValue ?
                new ObjectParameter("IDD", iDD) :
                new ObjectParameter("IDD", typeof(int));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountUroki", iDPParameter, iDGParameter, iDDParameter, dATParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CountUroki_Otchet_interval(Nullable<int> iDP, Nullable<int> iDG, Nullable<int> iDD, Nullable<System.DateTime> dAT_N, Nullable<System.DateTime> dAT_K)
        {
            var iDPParameter = iDP.HasValue ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(int));
    
            var iDGParameter = iDG.HasValue ?
                new ObjectParameter("IDG", iDG) :
                new ObjectParameter("IDG", typeof(int));
    
            var iDDParameter = iDD.HasValue ?
                new ObjectParameter("IDD", iDD) :
                new ObjectParameter("IDD", typeof(int));
    
            var dAT_NParameter = dAT_N.HasValue ?
                new ObjectParameter("DAT_N", dAT_N) :
                new ObjectParameter("DAT_N", typeof(System.DateTime));
    
            var dAT_KParameter = dAT_K.HasValue ?
                new ObjectParameter("DAT_K", dAT_K) :
                new ObjectParameter("DAT_K", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CountUroki_Otchet_interval", iDPParameter, iDGParameter, iDDParameter, dAT_NParameter, dAT_KParameter);
        }
    
        public virtual int MergePlan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MergePlan");
        }
    
        public virtual ObjectResult<pr_LoadGroup_Result> pr_LoadGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoadGroup_Result>("pr_LoadGroup");
        }
    
        public virtual ObjectResult<pr_LoadNagrGroup_Result> pr_LoadNagrGroup(Nullable<int> iDG)
        {
            var iDGParameter = iDG.HasValue ?
                new ObjectParameter("IDG", iDG) :
                new ObjectParameter("IDG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoadNagrGroup_Result>("pr_LoadNagrGroup", iDGParameter);
        }
    
        public virtual ObjectResult<pr_LoadNagrPrepod_Result> pr_LoadNagrPrepod(Nullable<int> iDP)
        {
            var iDPParameter = iDP.HasValue ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoadNagrPrepod_Result>("pr_LoadNagrPrepod", iDPParameter);
        }
    
        public virtual ObjectResult<pr_LoadPlan_Result> pr_LoadPlan(Nullable<int> iDP, Nullable<int> iDG, Nullable<int> iDD)
        {
            var iDPParameter = iDP.HasValue ?
                new ObjectParameter("IDP", iDP) :
                new ObjectParameter("IDP", typeof(int));
    
            var iDGParameter = iDG.HasValue ?
                new ObjectParameter("IDG", iDG) :
                new ObjectParameter("IDG", typeof(int));
    
            var iDDParameter = iDD.HasValue ?
                new ObjectParameter("IDD", iDD) :
                new ObjectParameter("IDD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoadPlan_Result>("pr_LoadPlan", iDPParameter, iDGParameter, iDDParameter);
        }
    
        public virtual ObjectResult<pr_LoadPrepod_Result> pr_LoadPrepod()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_LoadPrepod_Result>("pr_LoadPrepod");
        }
    }
}
