//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANtemp
    {
        public int IDN { get; set; }
        public int IDP { get; set; }
        public int IDG { get; set; }
        public int IDD { get; set; }
    }
}
