//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPGRUP
    {
        public int IDG { get; set; }
        public Nullable<int> IDO { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> IDA { get; set; }
        public Nullable<int> IDP { get; set; }
        public Nullable<short> IG { get; set; }
        public Nullable<int> IDF { get; set; }
        public Nullable<short> KURS { get; set; }
        public Nullable<int> IDV { get; set; }
        public bool FINAL { get; set; }
        public Nullable<System.DateTime> DATNN { get; set; }
        public Nullable<System.DateTime> DATKK { get; set; }
        public Nullable<int> kolStud { get; set; }
        public string NAIM { get; set; }
    }
}
