//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPNAGR
    {
        public int IDN { get; set; }
        public Nullable<int> IDP { get; set; }
        public Nullable<int> IDG { get; set; }
        public Nullable<int> IDD { get; set; }
        public Nullable<int> IDT { get; set; }
        public Nullable<int> IDA { get; set; }
        public Nullable<short> CHSEM { get; set; }
        public Nullable<System.DateTime> DATNN { get; set; }
        public Nullable<System.DateTime> DATKK { get; set; }
        public Nullable<short> CH { get; set; }
        public Nullable<byte> IDGG { get; set; }
        public Nullable<short> NAZNA { get; set; }
        public bool Po_Zam { get; set; }
        public Nullable<short> K_UR { get; set; }
        public Nullable<int> IN { get; set; }
        public string MEMO { get; set; }
        public Nullable<short> CZP { get; set; }
        public Nullable<short> CDO { get; set; }
        public Nullable<short> CUR { get; set; }
        public Nullable<float> UR_DAY { get; set; }
        public Nullable<short> CPL { get; set; }
        public bool PRAKT { get; set; }
        public bool WITHD { get; set; }
        public Nullable<short> CZPD { get; set; }
        public Nullable<short> PRAKD { get; set; }
        public Nullable<short> CURP { get; set; }
        public Nullable<float> UR_DAYP { get; set; }
        public Nullable<int> IDZ { get; set; }
        public Nullable<int> IDNN { get; set; }
        public bool NO_CALC { get; set; }
    }
}
