//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPPRED
    {
        public int IDD { get; set; }
        public string KOD { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> TRUD { get; set; }
        public string NAIM { get; set; }
    }
}
