//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedulePlanner
{
    using System;
    using System.Collections.Generic;
    
    public partial class UROKI
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DAT { get; set; }
        public Nullable<int> UR { get; set; }
        public Nullable<int> IDP { get; set; }
        public Nullable<int> IDG { get; set; }
        public Nullable<int> IDGG { get; set; }
        public Nullable<int> IDA { get; set; }
        public Nullable<int> IDD { get; set; }
        public Nullable<int> IDN { get; set; }
        public Nullable<int> IDR { get; set; }
        public bool ZP { get; set; }
        public bool MORE { get; set; }
        public Nullable<int> IDI { get; set; }
        public Nullable<int> IDNN { get; set; }
        public Nullable<int> IDU { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public bool HAND { get; set; }
    }
}
